apiVersion: v1
kind: Service
metadata:
  name: jira-service
  namespace: jira
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: |
      Environment=Development,Owner=nunnikrishnan@altimetrik.com,Project=Development,Application=Chatbot
spec:
  type: LoadBalancer
  selector:
    app: jira
  ports:
    - port: 30000
      targetPort: 8080
