apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: jira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "jirauser"
            - name: PGDATA
              value: /var/lib/postgresql/new_data/pgdata
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: POSTGRES_DB
              value: "jiradbb"
          volumeMounts:
            - mountPath: /var/lib/postgresql/new_data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc

